name: Auto Merge

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Auto-merge Renovate PRs
        if: github.actor == 'renovate[bot]' || github.actor == 'dependabot[bot]'
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: ""
          MERGE_METHOD: merge
          MERGE_COMMIT_MESSAGE: pull-request-title
          MERGE_FORKS: false
          MERGE_RETRIES: 6
          MERGE_RETRY_SLEEP: 10000
          UPDATE_LABELS: ""
          UPDATE_METHOD: merge
